sonar.projectKey=Carabin3_Proyecto-Final
sonar.organization=carabin3

# Esto le dice a Sonar qué archivos analizar
sonar.sources=.

# Esto excluye carpetas que no necesitas analizar (como node_modules)
sonar.exclusions=**/node_modules/**, **/dist/**

# Codificación de los archivos
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io